config/routes.rb
Demo::Application.routes.draw do
 
root :to => 'site#index' 

resources :work_requests 
 
 
namespace :admin do
	match '/' => 'dashboard#index'
	resources :work_requests
end 



end

app/models/work_request.rb
class WorkRequest < ActiveRecord::Base
  attr_accessible :name, :address, :phone, :problem
  
  validates :name, :address, :phone, :problem, :presence => true
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

	def index
	@work_requests = WorkRequest.all
	end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate
	layout 'admin'
	
	USERNAME = "cain"
	PASSWORD = "password"
	
	private
	
		def authenticate
			authenticate_or_request_with_http_basic do |username, password|
				username == USERNAME && password == PASSWORD
			end
			
		end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

def index
		@work_request = WorkRequest.new
	end
end 

app/controllers/work_requests_controller.rb
class WorkRequestsController < ApplicationController

	def create
	
	@work_request = WorkRequest.new(params[:work_request])
	
		if @work_request.save
			#send email to worker
			Ticket.notification(@work_request).deliver
			
			#good job
			flash[:success] = "Your Work Request has been submitted."
			redirect_to(root_path)
		else
			flash[:error] = "There was an error submitting your request."
			render('site/index')
		end
	
	
	end
	



end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_helper_method
	
		[:success, :error].each do |flash_key|
		
			return content_tag(:p, flash[flash_key], :class => "flash_#{flash_key}") if flash[flash_key]
		
		end unless flash.blank?
	
	end

end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/work_requests_helper.rb
module WorkRequestsHelper
end

app/views/admin/dashboard/index.html.erb
<h1> Admin Dashboard </h1>

<table border="0" cellspacing="0" cellpadding="0">
	<tr>
		<th>Name<th>
		<th>Phone<th>
		<th>Address<th>
		<th>&nbsp;<th>
		<th>&nbsp;<th>
	</tr>




<% @work_requests.each do |wr| %>

	<tr>
		<td><%= wr.name %></td>
		<td><%= wr.phone %></td>
		<td><%= wr.address %></td>
		<td><%= link_to('edit', [:admin, wr]) %></td>
		<td><%= link_to('delete', [:admin, wr], :method => :delete, :confirm => "Are you sure?") %></td>
		
	</tr>



<% end %>

</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to('Home Page', root_path) %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/index.html.erb
<%= flash_helper_method %>

<h1>Home Page</h1>
<%= Date.today %>

<%= form_for(@work_request) do |f| %>

	<p>
	
	<%= f.label(:name) %> 
	<%= f.text_field(:name) %>

	</p>

	<p>

	<%= f.label(:address) %> 
	<%= f.text_field(:address) %>
	
	</p>	
	
	<p>
	
	<%= f.label(:phone) %> 
	<%= f.text_field(:phone) %>

	</p>
	
	<p>

	<%= f.label(:problem) %> 
	<%= f.text_area(:problem) %>

	</p>


	<p> 
	<%= f.submit('Submit Work Request') %>
	
	</p>


<% end %>

app/views/ticket/notification.html.erb
<h1>New Ticket!</h1>
<p>Submitted at <%= @time %></p>
<br> <br>
<p>Name: <%= @work_request.name %><p>
<p>Address: <%= @work_request.address %><p>
<p>Phone: <%= @work_request.phone %><p>
<%= link_to('View this ticket', admin_url) %>